name: "Pylint Pip 24.1"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Check pip version
      run: |
        pip --version
 
    - name: Install Dev deps
      run: |
        pip install -r src/requirements-dev.txt
    - name: Install normal deps
      run: |
        pip install -r src/requirements.txt
